name: day5ui
description: A new Flutter project.
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
    provider: ^3.2.0
    logger: ^0.7.0+2
    get_it: ^3.0.3
    equatable: ^1.0.1
dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/